apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskservice
  template:
    metadata:
      labels:
        app: taskservice
    spec:
      containers:
        - name: taskservice
          image: taskservice:latest   
          imagePullPolicy: Never      
          ports:
            - containerPort: 8080
